version: '3'

services:
  nodejs:
    container_name: nest_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    volumes:
      - .:/app
    environment:
      OPENAI_API_KEY: OPENAI_API_KEY=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
      POSTGRES_HOST: c-demo-database-for-model.yrn4rb6hrtz2ht.postgres.cosmos.azure.com
      POSTGRES_PORT: 5432
      POSTGRES_USERNAME: citus
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DATABASE_NAME: demo-siampiwat
    restart: unless-stopped